### ISSUE TITLE
No module named 'mmfashion'

### ISSUE THREAD

**Issue by JaydenGG** [open-mmlab/mmfashion#1]
After install the package successfully.

I run the test command
python tools/test_predictor.py \
    --config configs/attribute_predict/roi_predictor_vgg_attr.py \
    --checkpoint checkpoint/Predict/vgg/roi/latest.pth

I get the error:  ModuleNotFoundError: No module named 'mmfashion'

But I check the pip list and find it contains the mmfashion:
mmfashion              0.1.0+27f4f53

**Comment by veralauee** [comment]
Please make sure you used python3 and implemented "python setup.py install".

**Comment by Steve-AI-Guy** [comment]
Same issue

**Comment by Steve-AI-Guy** [comment]
Same issue here.

**Comment by donghaoye** [comment]
Same issue here.

**Comment by lijiancheng0614** [comment]
It works with `python setup.py develop` before, now it works with `python setup.py install` too.
