### ISSUE TITLE
How to predict single img's attribute?

### ISSUE THREAD

**Issue by Arthurzhangsheng** [open-mmlab/mmfashion#10]
Thanks for your great work!
And I have a question here, how to predict my own imgs' attribute? Is there a simple api to predict one single img's attribute/box/landmark？

**Comment by veralauee** [comment]
Hi, we add the 'demo' in 'demo' folder. Please refer to "demo/test_predictor.py" for single image prediction.

**Comment by KuChiaChun** [comment]
Hi, is the pre-trained model for landmark detection just for full-body clothes ?
Thanks a lot for your work !

**Comment by veralauee** [comment]
@KuChiaChun 
We do not train the landmark detection model specifically for full-body clothes. But you can directly apply the pretrained model on full-body clothes.
