### ISSUE TITLE
Question about the top-k retrieval accuarcy 

### ISSUE THREAD

**Issue by WangQinghuCS** [open-mmlab/mmfashion#11]
Hello, I have a question about the top-k retrieval accuarcy. In the paper, it says 'a successful retrieval is counted if the exact fashion item has been found in the top-k retrieved results.' and in the paper 'Where to buy it?' , top-k accuracy is defined as  "the percentage of queries with at least one matching item retrieved within the ﬁrst k results." Are they the same？
 And in the released code, the topk retrieval accuarcy is calculated by the (tp) / (relevant_num) where tp means the num of exact fashion item has been found in the top-k retrieved results, the relevant_num means the num of cloth in gallery_set which has the same item_id as the query.
So I am confused,Can anyone give me some advice?

**Comment by veralauee** [comment]
Top-K retrieval accuracy is 'a successful retrieval is counted if the exact fashion item has been found in the top-k retrieved results.' 

In our code, tp means the num of exact fashion item has been found in the top-k retrieved results, relevant num means the num of right answers in gallery_set (which has the same item_id ). 
We need to ensure that if the right answers in gallery set are included in the top-k retrieved clothes, (k> the num of right answers), the accuracy should still be 1, because all the right answers are retrieved.

**Comment by WangQinghuCS** [comment]
> Top-K retrieval accuracy is 'a successful retrieval is counted if the exact fashion item has been found in the top-k retrieved results.'
> 
> In our code, tp means the num of exact fashion item has been found in the top-k retrieved results, relevant num means the num of right answers in gallery_set (which has the same item_id ).
> We need to ensure that if the right answers in gallery set are included in the top-k retrieved clothes, (k> the num of right answers), the accuracy should still be 1, because all the right answers are retrieved.

Thanks for your reply! But I still don't understand. According to the  'a successful retrieval is counted if the exact fashion item has been found in the top-k retrieved results.', I think top-k retrieved accuracy should be calculated in this way: the accuracy should  be 1 as long as one exact fashion item is found in the top-k retrieved results rather than the  (tp) / (relevant_num).  By the way, I want to know in the Consumer-to-Shop task, is the top-k retrieved accuracy  calculated as the  (tp) / (relevant_num)?

**Comment by veralauee** [comment]
'A successful retrival is counted  if the exact fashion item has been found in the top-k retrieved results.' means "if top-k retrieval results contains the true positive example, this retrieval is considered correct'.

We will implement Consumer-to-Shop task later on, but the evalutaion metric should be same

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
