### ISSUE TITLE
problems of fashion parsing and segmentation

### ISSUE THREAD

**Issue by stoensin** [open-mmlab/mmfashion#139]
# hi! 
## my env is ：
  mmcv                               0.5.1        
  mmdet                              2.0.0+ffeb3af
  mmfashion                          0.4.0        
  torch                              1.3.1+cu100  
  torchvision                        0.4.2+cu100
  
## Fashion Segmentation
|   Backbone  |  Model type  |       Dataset       |  bbox detection Average Precision  | segmentation Average Precision |      Download (Google)      |
| :---------: | :----------: | :-----------------: | :--------------------------------: | :----------------------------: | :-------------------------: |
|   Resnet50  |   Mask RCNN  | DeepFashion-In-shop |                0.599               |              0.584             |  [model](https://drive.google.com/open?id=1q6zF7J6Gb-FFgM87oIORIt6uBozaXp5r)   |

# the config is [：here](https://github.com/open-mmlab/mmfashion/blob/0e26ab36847684fbf7f736c39df8d518129d9a69/configs/fashion_parsing_segmentation/mask_rcnn_r50_fpn_1x.py#L2)

##while working with this code:
model = init_detector(args.config, args.checkpoint, device='cuda:0')
##got an error:
TypeError: __init__() got an unexpected keyword argument 'bbox_roi_extractor'

##As  the md file says that: 
Requirements
PyTorch 1.3.0
mmcv 0.5.1
Pillow 6.2.2
in [this page](https://github.com/open-mmlab/mmfashion/tree/master/configs/fashion_parsing_segmentation#requirements)

## Now i think i need some help!

**Comment by v-prgmr** [comment]
by far one of the horribly maintained projects, i should stop taking openmmlab seriously for any of the mentioned features.
