### ISSUE TITLE
Does not support windows

### ISSUE THREAD

**Issue by DominicDataScienctist** [open-mmlab/mmfashion#14]
somewhere in this package require torch.distributed:

https://github.com/open-mmlab/mmfashion/blob/7a5acde6cc9ddc92e4db44eeca88baa038443b38/mmfashion/datasets/loader/sampler.py#L7

which is not supported by windows version of pytorch

**Comment by veralauee** [comment]
We have not implemented Windows version yet. 
So far we only support Linux.

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
