### ISSUE TITLE
Top-5 Recall vs Top-5 Acc.	

### ISSUE THREAD

**Issue by DominicDataScienctist** [open-mmlab/mmfashion#16]
@veralauee 

Hello, can you kindly explain the difference between Top-5 Recall and Top-5 Acc. for attributes prediction?

**Comment by veralauee** [comment]
recall = True positive / total test number
accuracy = (True positive + True negative) / total test number
________________________________
发件人: Dom <notifications@github.com>
发送时间: 2019年12月17日 13:48
收件人: open-mmlab/mmfashion <mmfashion@noreply.github.com>
抄送: Xin Liu <xin.liu4@duke.edu>; Mention <mention@noreply.github.com>
主题: [open-mmlab/mmfashion] Top-5 Recall vs Top-5 Acc. (#16)


@veralauee<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_veralauee&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=K1LJAkHG0tA0XP79Oj1eEFArk8IivKL6H6U65DyRCGw&m=E92sKE1d1rKhKtXUdVIZ5FKnV2LSz__XMMfnIYkET9w&s=nxSt8bIrYby3JBLYqLFr3E2MG5bSXFmozjXiZTiED_c&e=>

Hello, can you kindly explain the difference between Top-5 Recall and Top-5 Acc. for attributes prediction?

―

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
