### ISSUE TITLE
[Help wanted] Error when using my own custom split for in-shop clothes retrieval

### ISSUE THREAD

**Issue by Lotayou** [open-mmlab/mmfashion#17]
@veralauee Hi, thanks for your effort for making things run smoothly. I have successfully evaluated the retriever on my machine with official query/gallery split. But when I evaluate the retriever on my own split I find the following error, of which I have got no clue. Can you help me with my issue or show me a workaround? Thanks in advance.

## Problem description

```
(lingbo) lingbo.ylb@vg:~/projects/mmfashion$ sh retrieval.sh 
2019-12-19 10:42:25,501 - INFO - Distributed test: False
dataset loaded
2019-12-19 10:42:37,289 - INFO - load model from: /home/lingbo.ylb/.cache/torch/checkpoints/resnet50-19c8e357.pth
pretrained model /home/lingbo.ylb/.cache/torch/checkpoints/resnet50-19c8e357.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

model built
load checkpoint from: checkpoints/retrieval_clothes_resnet50/epoch_150.pth
Traceback (most recent call last):
  File "tools/test_retriever.py", line 88, in <module>
    main()
  File "tools/test_retriever.py", line 84, in main
    logger=logger)
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3.7.egg/mmfashion/apis/test_retriever.py", line 40, in test_retriever
    _non_dist_test(model, query_set, gallery_set, cfg, validate=validate)
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3.7.egg/mmfashion/apis/test_retriever.py", line 84, in _non_dist_test
    e.evaluate(query_embeds_np, gallery_embeds_np)
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3.7.egg/mmfashion/core/evaluation/retrieval_eval.py", line 85, in evaluate
    gallery_embeds, i)
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3.7.egg/mmfashion/core/evaluation/retrieval_eval.py", line 66, in single_query
    relevant_num = len(self.gallery_id2idx[query_id])
KeyError: 1801
```
Here is my retrieval script
```
python tools/test_retriever.py \
    --config configs/retriever/roi_retriever_resnet.py \
    --checkpoint checkpoints/retrieval_clothes_resnet50/epoch_150.pth
```

My guess is that there is certain rule for creating a valid query/gallery split, and I definitely violate some sort of rule here. Here I detail my preparation of custom split to help you replicate the error.

## Preparation of my custom split
I am replicating an project on pose-guided human image generation, and somehow I wish to run a retrieval test using synthesized images to query from the real images. To this end, I simply set all the test images as "query" and all the train images as "gallery". 

Here is my train/test split, and I think the partition is completely random, and by principle the ids in training split and testing split **do not overlap**, (but I haven't verified it yet). Could this be the reason why I cannot find a corresponding item for my query in the gallery?

[test.txt](https://github.com/open-mmlab/mmfashion/files/3981544/test.txt)
[train.txt](https://github.com/open-mmlab/mmfashion/files/3981545/train.txt)

After that I created an `list_custom_patition.txt` inside `./data/In-shop/Eval`:
[list_custom_partition.txt](https://github.com/open-mmlab/mmfashion/files/3981551/list_custom_partition.txt)

Then I ran the `prepare-in-shop.py` script on the custom split file, and it all went well with no errors. Here are the generated annotations in a zip.
[Anno.zip](https://github.com/open-mmlab/mmfashion/files/3981552/Anno.zip)

## How to replicate my error
I think by downloading the annotation files attached above and replace the custom file should do the trick. However, in case something went wrong with my preparation, here I attach my python script for generation `list_custom_partition.txt` from my train/test files.
```
################
# Step #1: Use PATN test as query and train as gallaery, replace MMFashion's default split.
# Potential bug:
#	For each test image there could be multiple synthesized results as query (using different source images)
#	In this case, I just copy the testing line twice/thrice and evaluate the topK-recall multiple times.
################

import os
import pandas

# you may want to change the prefix.
PREFIX = '/home/lingbo.ylb/projects/Pose-Transfer-mod/fashion_data'

# We don't need training lines.

# convert compact string to directory
# Input be like: fashionWOMENSkirtsid0000062904_3back.jpg
# Output be like: img/WOMEN/Skirts/id_00000629/04_3_back.jpg
def convert(dirty_str):
	s = dirty_str.strip('\n')[7:] # remove fashion
	if s.startswith('MEN'):
		gender='MEN'
		s = s[3:]
	else:
		gender='WOMEN'
		s = s[5:]

	t = s.find('id000')
	clothes_type = s[:t]
	s = s[t+2:]  # skip 'id'
	id_num = s[:8]  # id is eight digits
	s = s[8:]   # 04_3back.jpg
	delim = s[:4]   # 04_3
	ext = s[4:]

	return id_num, 'img/{}/{}/id_{}/{}_{}'.format(gender, clothes_type, id_num, delim, ext)

gallery_list = os.path.join(PREFIX, 'train.lst')
query_list = os.path.join(PREFIX, 'test.lst')

with open(gallery_list, 'r') as f:
	gallery_items = [convert(s) for s in f]

with open(query_list, 'r') as f:
	query_items = [convert(s) for s in f]

#print(query_items[0:10])
# print(query_items)
n = len(gallery_items) + len(query_items)

output = '/home/lingbo.ylb/projects/mmfashion/data/In-shop/Eval/list_custom_partition.txt'
with open(output, 'w') as f:
	f.write('%d\nimage_name item_id evaluation_status\n' % n)
	for g in gallery_items:
		f.write('{:<72s}{} gallery\n'.format(g[1],g[0]))
	for q in query_items:
		f.write('{:<72s}{} query\n'.format(q[1],q[0]))
```

Thanks again for your time!

**Comment by Lotayou** [comment]
@veralauee I've been stucking on thisissue for a week, can you help? Thanks:P

**Comment by veralauee** [comment]
Sorry, I don't understand what exactly your problem is. 
Seemingly there is no 1-1 matching relationship(1 query and 1 gallery) in your train.txt or test.txt. Did you check there exist two same id number in your dataset?

**Comment by Lotayou** [comment]
@veralauee Okay now I understand the constraints. For my task the person ids are deliberately separated to guarantee the generalizability of the generative model. However for retrieval there must exist at least one corresponding gallery image with the same id number as the query, otherwise the retrieval system would raise the keyerror.

However, there must be some occasions in real life where you just don't have the correponding gallery item for the given query, and I suppose a proper response for the system should be a return message of "No item found" instead of simply raise an error. Maybe some try-exception mechanism could be introduced to the retriever to enhance the robustness. Hope to see this change in later versions. Thanks!
