### ISSUE TITLE
Demo for landmark detection

### ISSUE THREAD

**Issue by fluctlux** [open-mmlab/mmfashion#19]
Thanks for your great work!
Is there a simple way to get one single img's landmark

**Comment by veralauee** [comment]
The simplest way now is feed the dataset with just one image. We will release the landmark detection demo soon.

**Comment by veralauee** [comment]
> Thanks for your great work!
> Is there a simple way to get one single img's landmark

I just uploaded the landmark detect demo code. Now you can use it,

`python demo/test_landmark_detector.py --input [your input image] --checkpoint [pretrained weights]`

**Comment by veralauee** [comment]
Landmark detection demo has been released, so I will close it.
