### ISSUE TITLE
how to inference one image? just for clothes Detection

### ISSUE THREAD

**Issue by iot-hunter** [open-mmlab/mmfashion#2]

**Comment by veralauee** [comment]
What does "clothes detection" mean here? landmark detection or detect clothes? 
For landmark detection, you can make your own testing list (e.g., test.txt), just put one line in this file.
Fort clothes detection, we have not supported this task yet.

**Comment by iot-hunter** [comment]
"clothes detection" mean   detect clothes .    now   I use DeepFashion dataset to train detect net    use my dataset to train classfiy net . so I want to test your model for detect clothes    I have train yolov3 use DeepFashion Dataset , but the effect is not good

**Comment by veralauee** [comment]
> "clothes detection" mean detect clothes . now I use DeepFashion dataset to train detect net use my dataset to train classfiy net . so I want to test your model for detect clothes I have train yolov3 use DeepFashion Dataset , but the effect is not good

We haven't supported "clothes detect" yet. So the released model cannot be used.

**Comment by iot-hunter** [comment]
ok   thank you very much

**Comment by liuziwei7** [comment]
In the v0.1 version, we assume the clothes bounding box is given. We will include "Fashion Detection, Parsing and Segmentation" in our next release (1~2 months from now).
