### ISSUE TITLE
When will you release demo for retriever_consumer_to_shop

### ISSUE THREAD

**Issue by xu1718191411** [open-mmlab/mmfashion#23]
Thank you for your contribution
I am looking forward to run a demo for retriever_consumer_to_shop, will you release that soon?

**Comment by veralauee** [comment]
Thanks for your watching.

We just released the codes for retriever_consumer_to_shop, you can try it via
`python tools/train_retriever.py --config configs/retriever_consumer_to_shop/roi_retriever_vgg.py`

For demo, you can simply replace the pretrained model of "in-shop retriever". We are reformating the demo code and release it in Jan.

**Comment by xu1718191411** [comment]
Thank you very much!
