### ISSUE TITLE
Error about 'idx2id'

### ISSUE THREAD

**Issue by xu1718191411** [open-mmlab/mmfashion#26]
python tools/test_retriever.py     --config configs/retriever_in_shop/roi_retriever_vgg.py     --checkpoint checkpoint/Retrieve_in_shop/vgg/epoch_100.pth

When I execute it like this I got the following error

__init__() got an unexpected keyword argument 'idx2id'

When I try to find the reference from configs/retriever_in_sjop/roi_retriever_vgg.py
I find the following definition in query and gallery dict.
idx2id=os.path.join(data_root, 'Anno/query_idx2id.txt')

But after I execute /data/prepare_in_shop.py I find there does not have a file named query_idx2id.txt or gallery_idx2id.txt
Is this error caused by the data?

looking forward to your reply

**Comment by veralauee** [comment]
Sorry about the wrong setting. Actually we don't need this file. I just updated the config file. You can pull it and try again.

**Comment by xu1718191411** [comment]
Thank you! It works
