### ISSUE TITLE
How to extract detailed features for a clothes?

### ISSUE THREAD

**Issue by kaidaning** [open-mmlab/mmfashion#28]
Hi,
I was able to run the following code to obtain top 10 features of a clothes: 
python demo/test_predictor.py --config configs/attribute_predict/global_predictor_resnet_attr.py --checkpoint checkpoint/resnet/model_best_resnet_global.pth --input demo/attr_pred_demo2.jpg

Is there a way to extract more detailed features of an image in (e.g., a list of about 100 or 200 values)? I want to use these features to further check similarity of two clothes.

Thanks,
Kaida

**Comment by veralauee** [comment]
Of course you can. The default value of AttrPredictor is tops_type=[3, 5, 10].
You can re-define it in demo/test_predictor.py:
`attr_predictor = AttrPredictor(cfg.data.test, tops_type=[100, 200])`

**Comment by veralauee** [comment]
No more question about extracting features, I will close it.
