### ISSUE TITLE
Accuracy about in-shop retriever

### ISSUE THREAD

**Issue by xu1718191411** [open-mmlab/mmfashion#33]
As with the latest code by the commit of aea9b23a50487d725e322259faead782a18c0f30
I execute the code by 
```
python demo/demo/test_retriever.py 
```

the parse in test_retriever.py are the following

```
parser = argparse.ArgumentParser(
        description='MMFashion In-shop Clothes Retriever Demo')
    parser.add_argument(
        '--input',
        type=str,
        help='input image path',
        default='demo/retrieve_demo1.jpg')
    parser.add_argument(
        '--config',
        help='train config file path',
        default='configs/retriever_in_shop/global_retriever_vgg_loss_id.py')
    parser.add_argument(
        '--checkpoint',
        type=str,
        default='checkpoint/Retrieve/vgg/global/epoch_100.pth',
        help='the checkpoint file to resume from')
    parser.add_argument(
        '--use_cuda', type=bool, default=True, help='use gpu or not')
    args = parser.parse_args()
    return args
```
checkpoint/Retrieve/vgg/global/epoch_100.pth is downloaded from following

Backbone | Pooling | Loss | Top-5 Acc. | Download
VGG-16 | Global Pooling | Cross-Entropy | 38.76 | model

I got the following result:

```
pretrained model None
Retrived Top5 Results
Retrieved Image img/WOMEN/Jackets_Coats/id_00002609/02_3_back.jpg
Retrieved Image img/WOMEN/Tees_Tanks/id_00004096/06_1_front.jpg
Retrieved Image img/WOMEN/Jackets_Coats/id_00006337/02_4_full.jpg
Retrieved Image img/WOMEN/Shorts/id_00003973/06_2_side.jpg
Retrieved Image img/WOMEN/Shorts/id_00006962/01_2_side.jpg
```

The result still seems to be not correspond with the demo image 

I really want to present the same result as with the demo you show here
https://github.com/open-mmlab/mmfashion/blob/master/misc/demo_retrieval.gif

Can you give me some hint? Thank you

**Comment by veralauee** [comment]
> As with the latest code by the commit of [aea9b23](https://github.com/open-mmlab/mmfashion/commit/aea9b23a50487d725e322259faead782a18c0f30)
> I execute the code by
> 
> ```
> python demo/demo/test_retriever.py 
> ```
> 
> the parse in test_retriever.py are the following
> 
> ```
> parser = argparse.ArgumentParser(
>         description='MMFashion In-shop Clothes Retriever Demo')
>     parser.add_argument(
>         '--input',
>         type=str,
>         help='input image path',
>         default='demo/retrieve_demo1.jpg')
>     parser.add_argument(
>         '--config',
>         help='train config file path',
>         default='configs/retriever_in_shop/global_retriever_vgg_loss_id.py')
>     parser.add_argument(
>         '--checkpoint',
>         type=str,
>         default='checkpoint/Retrieve/vgg/global/epoch_100.pth',
>         help='the checkpoint file to resume from')
>     parser.add_argument(
>         '--use_cuda', type=bool, default=True, help='use gpu or not')
>     args = parser.parse_args()
>     return args
> ```
> 
> checkpoint/Retrieve/vgg/global/epoch_100.pth is downloaded from following
> 
> Backbone | Pooling | Loss | Top-5 Acc. | Download
> VGG-16 | Global Pooling | Cross-Entropy | 38.76 | model
> 
> I got the following result:
> 
> ```
> pretrained model None
> Retrived Top5 Results
> Retrieved Image img/WOMEN/Jackets_Coats/id_00002609/02_3_back.jpg
> Retrieved Image img/WOMEN/Tees_Tanks/id_00004096/06_1_front.jpg
> Retrieved Image img/WOMEN/Jackets_Coats/id_00006337/02_4_full.jpg
> Retrieved Image img/WOMEN/Shorts/id_00003973/06_2_side.jpg
> Retrieved Image img/WOMEN/Shorts/id_00006962/01_2_side.jpg
> ```
> 
> The result still seems to be not correspond with the demo image
> 
> I really want to present the same result as with the demo you show here
> https://github.com/open-mmlab/mmfashion/blob/master/misc/demo_retrieval.gif
> 
> Can you give me some hint? Thank you

I updated the demo code. You can pull the latest code and test it. 
You will get the results as follows,
`Retrieved Top5 Results
data/In-shop/data/In-shop/Img/img/WOMEN/Tees_Tanks/id_00000026/06_7_additional.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Tees_Tanks/id_00000026/06_4_full.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Tees_Tanks/id_00000026/06_2_side.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Dresses/id_00006555/04_1_front.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Cardigans/id_00001046/04_1_front.jpg
`

**Comment by veralauee** [comment]
I updated the demo code, you can pull it and re-test.
Hopefully, you will get the results as follows,
`Retrieved Top5 Results
data/In-shop/data/In-shop/Img/img/WOMEN/Tees_Tanks/id_00000026/06_7_additional.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Tees_Tanks/id_00000026/06_4_full.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Tees_Tanks/id_00000026/06_2_side.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Dresses/id_00006555/04_1_front.jpg
data/In-shop/data/In-shop/Img/img/WOMEN/Cardigans/id_00001046/04_1_front.jpg
`
