### ISSUE TITLE
about the retrieve

### ISSUE THREAD

**Issue by tantao14** [open-mmlab/mmfashion#35]
hello! i've met a problem ''NoneType' object has no attribute 'unsqueeze'' when i try the roi pooling model, the config file is '/roi_retriever_vgg_loss_id.py', i guess i should change line 'query_embed = model(img_tensor, landmark=None, return_loss=False)' in demo/test_retriever.py, but i don't know the input of landmark, could you please tell me? besides, if i want change the dataset to my own, when retrieving, which files should i generate before(i guess not all in data/In-shop need prepared)?

**Comment by tantao14** [comment]
i want to test single image, so i didn't use the file in tools

**Comment by gyuhwung** [comment]
what is landmark? i get the same error. how to pass that argument?
can you show us a demo of the retrieve with landmark pooling based models?

**Comment by veralauee** [comment]
> what is landmark? i get the same error. how to pass that argument?
> can you show us a demo of the retrieve with landmark pooling based models?

The manually written landmark is not enabled in current demo. 
One simple way is to create a landmark file following the format of "Deep-Fashion" landmark file, and then you can apply the roi-pooling models in demo codes.

**Comment by veralauee** [comment]
> i want to test single image, so i didn't use the file in tools

Did you use the demo codes? In such case, you cannot use roi_pooling configurations because no landmark is given in demo.

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
