### ISSUE TITLE
wrong code implementation?

### ISSUE THREAD

**Issue by gyuhwung** [open-mmlab/mmfashion#36]
normalized_error, det_percent = self.compute_distance(
            vis * pred_lm_np, vis * landmark_np)

shouldn't it be 

        normalized_error, det_percent = self.compute_distance(
            pred_vis * pred_lm_np, vis * landmark_np)

then the test result in modelzoo are wrong projection?

**Comment by gyuhwung** [comment]
Then, is this reslut trustworthy?

Backbone | Loss | Normalized Error | % of Det. Landmarks | Download
VGG-16 | L2 Loss | 0.0813 | 55.35 | model
ResNet-50 | L2 Loss | 0.0758 | 56.32 | model

**Comment by gyuhwung** [comment]
how come detected landmark value is negative
like
detected landmark 23.499176502227783 -84.74402720587594
detected landmark -19.22113159724644 12.215264184134346
detected landmark -53.55967477389744 -75.86981238637651
detected landmark -60.81352605138506 43.34355553558894
detected landmark -17.549434789589473 35.97311200414385

...guess i am asking too many questions..

**Comment by veralauee** [comment]
> ```
>     normalized_error, det_percent = self.compute_distance(
>         vis * pred_lm_np, vis * landmark_np)
> ```
> 
> shouldn't it be
> 
> ```
>     normalized_error, det_percent = self.compute_distance(
>         pred_vis * pred_lm_np, vis * landmark_np)
> ```
> 
> then the test result in modelzoo are wrong projection?

The implementation is not wrong. Cuz we consider the visibility as pre-condition, we don't need to predict it in advance.

**Comment by veralauee** [comment]
Since no more question about this implementation. I will close it.
