### ISSUE TITLE
qs about img dataset

### ISSUE THREAD

**Issue by lookdeceline** [open-mmlab/mmfashion#37]
Thank you for the awesome dataset and codes.

In "img" directory of your dataset, 
what is the difference between img/CLOTHING/pants vs img/TROUSERS/pants ??
I see the id numbers are different inside each directory, but why do we need two separate "pants" category??

**Comment by veralauee** [comment]
Visually it might has little difference. Such categorization might aims to match the id. Overall, no special reason to make that.

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
