### ISSUE TITLE
Retrievimg top-k images for consumer-to-shop task?

### ISSUE THREAD

**Issue by lookdeceline** [open-mmlab/mmfashion#38]
Thank you for the awesome dataset and code. 

I have a question regarding one of your benchmarks,  consumer-to-shop image retrieval.
I may be wrong, but in your paper, it seems like the FashionNet does not output the result for consumer-to-shop image retrieval.
Which similarity measure did you use to retrieve top-k consumer-to-shop images ? 

Thanks a lot.

**Comment by veralauee** [comment]
The paper, e.g. FashionNet, has the result of consumer-to-shop image retrieval. We use the same measurement as the paper presents.

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
