### ISSUE TITLE
What is the expected output for the VGG(Attribute Prediction) model on the demo images

### ISSUE THREAD

**Issue by ashwath98** [open-mmlab/mmfashion#39]
These are the results I'm getting for the three demo images
1.
print
lace
knit
sleeve
floral

2.
lace
knit
print
sleeve
striped

3.

print
lace
knit
sleeve
striped

Which seems wrong
what is the suggested fix?

This is the command  I am running
!python demo/test_predictor.py --input demo/imgs/attr_pred_demo3.jpg --checkpoint checkpoints/latest.pth

latest.pth is the VGG backbone global pooling model
and I have used list_attr_clothing.txt file provided on the deepfashion site

**Comment by veralauee** [comment]
It is not fixed. 1, 2, 3 are different. It is possibly that  "print" in the dataset are major attribute, so the pretrained model has some bias.

**Comment by ashwath98** [comment]
Okay. Thank you for the clarification 😊

**Comment by veralauee** [comment]
Will close the issue.
