### ISSUE TITLE
can't download models zoo from google drive

### ISSUE THREAD

**Issue by nwf5d** [open-mmlab/mmfashion#42]
I can't download models zoo files from google drive because I'm in chinese mainland.
Would you give a resouce link of Baidu Cloud(pan.baidu.com) or 360 Cloud?
Thank you!

**Comment by liuziwei7** [comment]
Thanks for the feedback. We will upload all pre-trained models onto Baidu Drive this week.

**Comment by liuziwei7** [comment]
The pre-trained models are now accessible on Baidu Drive as well. Please refer to "model zoo" section for more details.
