### ISSUE TITLE
Visualizing the generated landmarks

### ISSUE THREAD

**Issue by ashwath98** [open-mmlab/mmfashion#46]
Hi,
I am able to predict the landmarks using your model.

Could I know how to go about visualizing the landmarks on the images
If the feature is not there how would you recommend I add it? ( Basic Open CV?)
Thanks

**Comment by veralauee** [comment]
You can matplot to draw some marks using the predicted landmark(x and y coordinates) on the image.

**Comment by veralauee** [comment]
Close this issue.
