### ISSUE TITLE
Content of "list_attr_cloth.txt"

### ISSUE THREAD

**Issue by Edoardopericoli** [open-mmlab/mmfashion#48]
What should the **"list_attr_cloth.txt"** file contain when performing the **"test_predictor.py**" on an image?

In order to test an image, I simply created an empty txt file, but it throws me a key error and I suspect the reason is that it expects something inside the txt.

Thank you.

**Comment by veralauee** [comment]
When testing the attribute predictor, the "list_attr_cloth.txt" should be the ground truth of the clothes attributes. It will be used to evaluate the prediction accuracy.
If you just would like to test a single image without ground truth, you don't need to provide this file. Please refer to demo/test_predictor.py

**Comment by Edoardopericoli** [comment]
Thank you for the explanation.

The error I get is related to something else then. Here a snapshot of it:

![Cattura](https://user-images.githubusercontent.com/43668053/80922446-7d400f00-8d7d-11ea-9bb0-597c6ef0ef06.PNG)

**Comment by veralauee** [comment]
> Thank you for the explanation.
> 
> The error I get is related to something else then. Here a snapshot of it:
> 
> ![Cattura](https://user-images.githubusercontent.com/43668053/80922446-7d400f00-8d7d-11ea-9bb0-597c6ef0ef06.PNG)

You can just use our provided "list_attr_cloth.txt". It is used just to initialize the attribute predictor, will not influence the prediction results.

**Comment by mitraavi** [comment]
I couldn't find this provided "list_attr_cloth.txt".
Could you please let us know location of this file in the repo ?
Thanks!

**Comment by mitraavi** [comment]
![Traceback_example](https://user-images.githubusercontent.com/37571218/81036132-8d5e0880-8ebb-11ea-966e-afc898d1bac8.png)

**Comment by mitraavi** [comment]
My apology! for stupid query ...the  file "list_attr_cloth.txt" exist in DeepFashion dataset repo, just downloaded it

**Comment by veralauee** [comment]
Close this issue since the file is found.
