### ISSUE TITLE
checkpoint/vgg16.pth

### ISSUE THREAD

**Issue by yiming-lzx** [open-mmlab/mmfashion#5]
hi ，how can i get the init model checkpoint/vgg16.pth ???

**Comment by veralauee** [comment]
You can download from pytorch official github site. 
 'vgg16': 'https://download.pytorch.org/models/vgg16-397923af.pth',

**Comment by msverma101** [comment]
this is a different vgg model.
i am getting this error 

python demo/test_landmark_detector.py --input /home/student_sneha/Downloads/git/thesis/2d_pose_mmpose/videoCamera.png0017.png  --checkpoint /home/student_sneha/Downloads/git/thesis/2d_pose_mmpose/checkpoint/vgg16.pth --config configs/landmark_detect/landmark_detect_vgg.py
/home/student_sneha/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
pretrained model /home/student_sneha/Downloads/git/thesis/2d_pose_mmpose/checkpoint/vgg16.pth
load checkpoint from local path: /home/student_sneha/Downloads/git/thesis/2d_pose_mmpose/checkpoint/vgg16.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: classifier.0.weight, classifier.0.bias, classifier.3.weight, classifier.3.bias, classifier.6.weight, classifier.6.bias

model built
load checkpoint from local path: /home/student_sneha/Downloads/git/thesis/2d_pose_mmpose/checkpoint/vgg16.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: features.0.weight, features.0.bias, features.2.weight, features.2.bias, features.5.weight, features.5.bias, features.7.weight, features.7.bias, features.10.weight, features.10.bias, features.12.weight, features.12.bias, features.14.weight, features.14.bias, features.17.weight, features.17.bias, features.19.weight, features.19.bias, features.21.weight, features.21.bias, features.24.weight, features.24.bias, features.26.weight, features.26.bias, features.28.weight, features.28.bias, classifier.0.weight, classifier.0.bias, classifier.3.weight, classifier.3.bias, classifier.6.weight, classifier.6.bias

missing keys in source state_dict: backbone.features.0.weight, backbone.features.0.bias, backbone.features.2.weight, backbone.features.2.bias, backbone.features.5.weight, backbone.features.5.bias, backbone.features.7.weight, backbone.features.7.bias, backbone.features.10.weight, backbone.features.10.bias, backbone.features.12.weight, backbone.features.12.bias, backbone.features.14.weight, backbone.features.14.bias, backbone.features.17.weight, backbone.features.17.bias, backbone.features.19.weight, backbone.features.19.bias, backbone.features.21.weight, backbone.features.21.bias, backbone.features.24.weight, backbone.features.24.bias, backbone.features.26.weight, backbone.features.26.bias, backbone.features.28.weight, backbone.features.28.bias, global_pool.global_layers.0.weight, global_pool.global_layers.0.bias, global_pool.global_layers.3.weight, global_pool.global_layers.3.bias, landmark_feature_extractor.linear.weight, landmark_feature_extractor.linear.bias, visibility_classifier.linear.weight, visibility_classifier.linear.bias, landmark_regression.linear.weight, landmark_regression.linear.bias

load checkpoint from: /home/student_sneha/Downloads/git/thesis/2d_pose_mmpose/checkpoint/vgg16.pth
detected landmark -2.4315694187368666 -0.29410123692027157
detected landmark 2.8554979179586684 0.2111292683652469
detected landmark 3.9886311228786195 -2.2035064548254013
detected landmark -3.702827574951308 2.222233542374202
