### ISSUE TITLE
Best configuration for Attribute Prediction

### ISSUE THREAD

**Issue by Edoardopericoli** [open-mmlab/mmfashion#52]
What is the best configuration (config file, checkpoint) to do attribute prediction on an image, according to your experiments?

**Comment by veralauee** [comment]
roi_predictor_resnet_attr.py
You can refer to model_zoo to check the performance of different models:
https://github.com/open-mmlab/mmfashion/blob/master/docs/MODEL_ZOO.md

**Comment by mitraavi** [comment]
I used below input arguments:
-------------------------------
--input demo/imgs/attr_pred_demo3.jpg
--config configs/attribute_predict/roi_predictor_resnet_attr.py
--checkpoint checkpoint/ResNet-50_landmark_Pooling_latest.pth

I'm getting below error:
---------------------------------------------------
tcmalloc: large alloc 1644167168

Traceback (most recent call last):
  File "demo/test_predictor.py", line 58, in <module>
    main()
  File "demo/test_predictor.py", line 51, in main
    attr_prob = model(img_tensor, attr=None, landmark=None, return_loss=False)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.1.0+5074927-py3.6.egg/mmfashion/models/predictor/base.py", line 41, in forward
    return self.forward_test(img, landmark)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.1.0+5074927-py3.6.egg/mmfashion/models/predictor/base.py", line 29, in forward_test
    return self.simple_test(img[0], landmark[0])

TypeError: 'NoneType' object is not subscriptable
---------------------------------------------------

Could you please tell me if I'm doing any wrong or it is bug in current version ?

**Comment by mitraavi** [comment]
I'm assuming landmark-pooling and roi-pooling are same, hence used the "ResNet-50_landmark_Pooling_latest.pth".
Also it seems base.py is expecting landmark parameter, is that the reason for the above error, please help!

**Comment by veralauee** [comment]
> I'm assuming landmark-pooling and roi-pooling are same, hence used the "ResNet-50_landmark_Pooling_latest.pth".
> Also it seems base.py is expecting landmark parameter, is that the reason for the above error, please help!

You are right. Landmark pooling is the RoI pooling. Please refer to details here: https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Liu_DeepFashion_Powering_Robust_CVPR_2016_paper.pdf
