### ISSUE TITLE
Some questions about training Consumer_to_shop

### ISSUE THREAD

**Issue by songwsx** [open-mmlab/mmfashion#56]
Reading attributes feels like there's something wrong.
https://github.com/open-mmlab/mmfashion/blob/1467baf44248fd624bc340eaafef0adae089bc07/mmfashion/datasets/Consumer_to_shop.py#L100

**Comment by songwsx** [comment]
我把改成了：
`  if a == '1'`
训练过程如下：
![image](https://user-images.githubusercontent.com/32413719/82114870-d5214180-9791-11ea-9ece-a55955c658d2.png)
loss_attr 还是非常小，不知道是否有问题？

**Comment by veralauee** [comment]
> 我把改成了：
> ` if a == '1'`
> 训练过程如下：
> ![image](https://user-images.githubusercontent.com/32413719/82114870-d5214180-9791-11ea-9ece-a55955c658d2.png)
> loss_attr 还是非常小，不知道是否有问题？

Generally no problem.
Consumer_to_shop dataset is used for clothes retrieval task. The losses that plays important role are the triplet loss and the loss_id( to enhance classification). The attribute of each cloth helps to add more information, so it will not affect the performance much.

Also, thanks for pointing out this error. We just modified it in the newer version.

**Comment by lulu867** [comment]
Have you got problems during the test of consume_shop retrieval ?When I tried to run the demo of consume_shop retrieval, there were always something wrong and I can't get through. Cound you please give me some instructions?
