### ISSUE TITLE
Is roi pooling as same as  landmark pooling?

### ISSUE THREAD

**Issue by Lytua** [open-mmlab/mmfashion#61]
I am quite confused about these two pooling methods, because I can't find any "roi pooling model" on the model zoo website. 

If I wanna use ResNet-50 + Landmark Pooling, could I use this configs: "roi_predictor_resnet_attr.py" ?
But I got the bug:
```
return self.simple_test(img[0], landmark[0])
TypeError: 'NoneType' object is not subscriptable
```

Thanks for anyone's help!

**Comment by veralauee** [comment]
Yes. RoI Pooling is the same as Landmark pooling.
