### ISSUE TITLE
Mistake in GETTING_STARTED.md

### ISSUE THREAD

**Issue by sunjinr** [open-mmlab/mmfashion#62]
In example 1 of *Test an image* it shows:
```python
# Prepare `Anno/list_attr_cloth.txt` which is specified in `configs/attribute_predict/global_predictor_vgg_attr.py`
python demo/test_predictor.py \
    --input demo/attr_pred_demo1.jpg
```

But the image path is wrong, it should be like *--input demo/imgs/attr_pred_demo1.jpg*.

**Comment by veralauee** [comment]
It's just a sample that tells the user how to use the command. You can set up the path of the demo images anywhere, it's not fixed.

**Comment by sunjinr** [comment]
I mean if your slogan includes *friendly*, you need to pay attention to these obvious and important guidance issues.
But whatever.

**Comment by veralauee** [comment]
> I mean if your slogan includes _friendly_, you need to pay attention to these obvious and important guidance issues.
> But whatever.

Thanks for your advice. We will modify it.
