### ISSUE TITLE
What does recommendation mean？

### ISSUE THREAD

**Issue by meanmee** [open-mmlab/mmfashion#64]
Does it mean given a pic of clothes, then the model can give some advices of fashion by giving some pics of other clothes?

**Comment by meanmee** [comment]
How to use recommendation function cuz for now I only see the get_compatity() fuction

**Comment by veralauee** [comment]
For instance, you give a T-shirt, "recommendation" will help find the most compatible pants, shoes and other accessories that match best with your T-shirt.
"compatibility" will give you a compatibility score of your outfits. Higher scores mean more compatible.

You can use demo/test_fashion_recommender.py to have a try.

**Comment by meanmee** [comment]
The test_fashion_recommender.py only provides a "compatibility" function. I don't see the
"recommendation" one.

**Comment by veralauee** [comment]
> The test_fashion_recommender.py only provides a "compatibility" function. I don't see the
> "recommendation" one.

You can offer a set of possible choices. And pick up the highest scored one.

**Comment by meanmee** [comment]
That is great, but I have tried it. It seems like for now this function only supports the cloth images in Polyvore dataset. How can I use this function to process my own data? like I take some photos of my own clothes then it can give me a compatibility score.

Btw, Is there any chance this project would add the "recommendation" function I mentioned in the future? Cuz I think that is a great tool for people who really care how they look like and want to have great dressing skills.

**Comment by veralauee** [comment]
This is a good point. While so far we only support the images in Polyvore dataset, because this dataset will offer text description, not just images. We will train a model without text description so that other images can also be tested.

**Comment by veralauee** [comment]
Close it since no further comments.
