### ISSUE TITLE
Error to load model

### ISSUE THREAD

**Issue by lapakva** [open-mmlab/mmfashion#66]
Hi, there, thanks for the great resource.
Could you please advice why I can not get attributes for demo image
I have loaded model from the model zoo for vgg global pooling...please see the error message below

python demo/test_predictor.py --input demo/imgs/attr_pred_demo1.jpg  --checkpoint latest.pth 
which: no hipcc in (/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin:/home/ec2-user/anaconda3/bin/:/usr/libexec/gcc/x86_64-amazon-linux/4.8.5:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/libexec/gcc/x86_64-amazon-linux/4.8.5:/opt/amazon/openmpi/bin:/opt/amazon/efa/bin/:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin)
The model and loaded state dict do not match exactly

unexpected key in source state_dict: roi_pool.linear.0.weight, roi_pool.linear.0.bias, concat.fc_fusion.weight, concat.fc_fusion.bias

Traceback (most recent call last):
  File "demo/test_predictor.py", line 57, in <module>
    main()
  File "demo/test_predictor.py", line 51, in main
    attr_predictor = AttrPredictor(cfg.data.test)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/core/evaluation/attr_predict_demo.py", line 16, in __init__
    attr_cloth_file = open(cfg.attr_cloth_file).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'data/Attr_Predict/Anno/list_attr_cloth.txt'

**Comment by veralauee** [comment]
Did you download the dataset first and then run `python prepare_attr_pred.py` ?

**Comment by veralauee** [comment]
Closed
