### ISSUE TITLE
How do I test the fashion parsing and segmentation module?

### ISSUE THREAD

**Issue by jis3613** [open-mmlab/mmfashion#72]
In the documents, other modules are well-explained but there are no instructions related to the parsing and segmentation module.
Nothing about it in GETTING_STARTED.md or DATA_PREPARATION.md .
Could you provide the instructions and code to test the parsing and segmentation module?

Thank you

**Comment by jis3613** [comment]
I figured it out
Thanks

**Comment by gibrit** [comment]
can you give some information how did you figure it ? .. it will be helpful for others .  

> I figured it out
> Thanks

**Comment by AaradhyaSaxena** [comment]
> I figured it out
> Thanks

@jis3613 Can you please mention how you did it? that will be really helpful.

**Comment by AaradhyaSaxena** [comment]
this might help:  [https://github.com/open-mmlab/mmfashion/tree/master/configs/fashion_parsing_segmentation](url)

**Comment by Meghraj-Webllisto** [comment]
@AaradhyaSaxena your link is empty. please mention how you did it.
