### ISSUE TITLE
Issues with DataParallel in mmfashion

### ISSUE THREAD

**Issue by liyuxuan89** [open-mmlab/mmfashion#75]
I try to set cuda_visible_devices as follows: 

os.environ["CUDA_VISIBLE_DEVICES"] = "2,3"

but when I train the model, cuda:0 is still being used and I get the error message:

RuntimeError: module must have its parameters and buffers on device cuda:2 (device_ids[0]) but found one of them on device: cuda:0

I'm wondering what's wrong.

Another question is that MMParallel supports only single gpu. 

```
class MMDataParallel(DataParallel):
    def scatter(self, inputs, kwargs, device_ids):
        return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)

    def train_step(self, *inputs, **kwargs):
        if not self.device_ids:
            return self.module.train_step(*inputs, **kwargs)

        assert len(self.device_ids) == 1, \
            ('MMDataParallel only supports single GPU training, if you need to'
             ' train with multiple GPUs, please use MMDistributedDataParallel'
             'instead.')
```
I'm wondering if it's a good idea to use MMDataParallel this way? 
```
# put model on gpus
    model = MMDataParallel(model, device_ids=cfg.gpus.train).cuda()
```

**Comment by liyuxuan89** [comment]
Plus, is there some errors with resnet50 backbone? Using vgg to train a attribute predictor, the code works fine. But when I switch to resnet50 backbone, I always get cuda out of memory. This shouldn't happened since I set the image per gpu to be really small.

**Comment by veralauee** [comment]
What is your GPU memory? What is the batchsize?
