### ISSUE TITLE
Data is password protected

### ISSUE THREAD

**Issue by kartikwar** [open-mmlab/mmfashion#82]
I downloaded the Dataset In-Shop Clothes Retrieval Benchmark Dataset . The high resolution images in this dataset are password protected. What password should I enter to access these files ?

**Comment by veralauee** [comment]
Please email the DeepFashion author to get the password.

**Comment by kartikwar** [comment]
Yes I filled a form and submitted. I got the password for the same. Thanks @veralauee

**Comment by KarymN** [comment]
can someone give me a password? The Author isn't responding?
