### ISSUE TITLE
OSError: ~ is not a checkpoint file

### ISSUE THREAD

**Issue by BitnaKeum** [open-mmlab/mmfashion#93]
Hello. I want to run this program but I have some problems.
I'm using the GPU in Google colaboratory.

According to "GETTING_STARTED.md", I'm trying to test an attribute predictor by this code.
`python demo/test_attr_predictor.py --input demo/imgs/attr_pred_demo1.jpg`

But when running this code, an error about wrong path occurs.
<br>
![capture](https://user-images.githubusercontent.com/37769713/91387767-eb4e9b80-e870-11ea-9db4-40ae0544d962.PNG)
In mmfashion/demo/test_attr_predictor.py, line 29, I think, 'attribute_predict' should be changed to 'attribute_predict_coarse'.
<br><br><br>

Although I have changed the code, another error occurs.
![image](https://user-images.githubusercontent.com/37769713/91388018-7b8ce080-e871-11ea-8bbf-08cc1c90c63f.png)

When I run other code, the same OSError occurs.
![image](https://user-images.githubusercontent.com/37769713/91388630-bcd1c000-e872-11ea-91a8-ce4cd954f9c6.png)

What's the matter? and how can I solve this problem?
I need your help! Thank you.

**Comment by Lytua** [comment]
@BitnaKeum Have you solved this problem?
